/**
 * 
 */
package net.sakilapp.shared.formdata;

import java.util.Date;
import java.util.Map;

import javax.annotation.Generated;

import org.eclipse.scout.rt.shared.data.form.ValidationRule;
import org.eclipse.scout.rt.shared.data.form.fields.AbstractFormFieldData;
import org.eclipse.scout.rt.shared.data.form.fields.AbstractValueFieldData;

/**
 * <b>NOTE:</b><br>
 * This class is auto generated by the Scout SDK. No manual modifications recommended.
 * 
 * @generated
 */
@Generated(value = "org.eclipse.scout.sdk.workspace.dto.formdata.FormDataDtoUpdateOperation", comments = "This class is auto generated by the Scout SDK. No manual modifications recommended.")
public abstract class AbstractMetadataBoxData extends AbstractFormFieldData {

  private static final long serialVersionUID = 1L;

  public AbstractMetadataBoxData() {
  }

  public Id getId() {
    return getFieldByClass(Id.class);
  }

  public LastUpdate getLastUpdate() {
    return getFieldByClass(LastUpdate.class);
  }

  public static class Id extends AbstractValueFieldData<Long> {

    private static final long serialVersionUID = 1L;

    public Id() {
    }

    /**
     * list of derived validation rules.
     */
    @Override
    protected void initValidationRules(Map<String, Object> ruleMap) {
      super.initValidationRules(ruleMap);
      ruleMap.put(ValidationRule.MAX_VALUE, Long.MAX_VALUE);
      ruleMap.put(ValidationRule.MIN_VALUE, Long.MIN_VALUE);
    }
  }

  public static class LastUpdate extends AbstractValueFieldData<Date> {

    private static final long serialVersionUID = 1L;

    public LastUpdate() {
    }
  }
}
